<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>! zeynep</title>
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@600&display=swap" rel="stylesheet" />
<style>
  body {
    margin: 0;
    font-family: 'Orbitron', sans-serif;
    color: #d1d1d1;
    display: flex;
    flex-direction: column;
    align-items: center;
    min-height: 100vh;
    position: relative;
    overflow: hidden;
  }
  body::before {
    content: "";
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    background: url('https://i.imgur.com/wOUWoGK.png') no-repeat center center fixed;
    background-size: cover;
    filter: blur(4px);
    z-index: -1;
    transform: scale(1.05);
    opacity: 0.95;
  }
  .glow-title {
    font-size: 3rem;
    margin-top: 80px;
    color: #ccc;
    text-shadow:
      0 0 6px #bbb,
      0 0 10px #aaa,
      0 0 15px #999;
  }
  .card {
    background: rgba(255, 255, 255, 0.07);
    border-radius: 20px;
    box-shadow: 0 0 25px rgba(200, 200, 200, 0.15);
    padding: 30px;
    margin: 50px 20px;
    width: 320px;
    text-align: center;
    backdrop-filter: blur(14px);
    border: 1px solid rgba(255, 255, 255, 0.15);
    z-index: 10;
  }
  .profile-pic {
    width: 120px;
    height: 120px;
    border-radius: 50%;
    border: 3px solid #ccc;
    box-shadow: 0 0 15px #ccc;
    object-fit: cover;
  }
  .username {
    margin: 20px 0 10px;
    font-size: 2rem;
    font-weight: 900;
    color: #a3cfff;
    text-shadow:
      0 0 8px #a3cfff,
      0 0 15px #70a8ff,
      0 0 20px #5b94e6;
    letter-spacing: 1.5px;
    transition: color 0.3s ease;
  }
  .username:hover {
    color: #d0eaff;
    text-shadow:
      0 0 12px #d0eaff,
      0 0 25px #9bd0ff,
      0 0 35px #7ab0ff;
  }
  .bio {
    font-size: 1rem;
    color: #bbb;
    margin-bottom: 25px;
  }
  .social-links {
    display: flex;
    justify-content: center;
    gap: 25px;
  }
  .social-link {
    display: flex;
    align-items: center;
    gap: 10px;
    text-decoration: none;
    color: #ccc;
    font-weight: 700;
    padding: 10px 15px;
    border-radius: 9999px;
    transition: all 0.3s ease;
  }
  .social-link:hover {
    color: #fff;
    text-shadow:
      0 0 5px #fff,
      0 0 10px #bbb,
      0 0 15px #aaa;
  }
  .social-link img {
    width: 26px;
    height: 26px;
  }
  @media (max-width: 400px) {
    .card {
      width: 90%;
    }
  }
</style>
</head>
<body>
  <h1 class="glow-title">! zeynep</h1>
  <div class="card">
    <img src="https://i.imgur.com/nmYRAUN.png" alt="Profil Fotoğrafı" class="profile-pic" />
    <div class="username">@zeynepcryptic</div>
    <div class="bio">Ne Koycamı Bilmiyorum LoL</div>
    <div class="social-links">
      <a href="https://www.instagram.com/zeynepcryptic/" target="_blank" class="social-link" rel="noopener noreferrer">
        <img src="https://cdn-icons-png.flaticon.com/512/174/174855.png" alt="Instagram" /> Instagram
      </a>
      <a href="https://discord.com/users/1207722195095265340" target="_blank" class="social-link" rel="noopener noreferrer">
        <img src="https://cdn-icons-png.flaticon.com/512/2111/2111370.png" alt="Discord" /> zeynep_gsm
      </a>
    </div>
  </div>

  <!-- Arka planda görünmez YouTube müzik iframe'i -->
  <iframe
    width="0"
    height="0"
    src="https://www.youtube.com/embed/zAQ9n1v1wIM?autoplay=1&loop=1&playlist=zAQ9n1v1wIM&controls=0&mute=0&modestbranding=1"
    frameborder="0"
    allow="autoplay"
    allowfullscreen
    style="display:none;"
  ></iframe>
</body>
</html>
